spring.datasource.url=jdbc:postgresql://ep-little-night-ap8j7kh6-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_9msnFESCNib6&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
